# Multiclass logistic regression / ordinal regression

In [10]:
import numpy as np
import mord as m
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

#Defining the model
c = m.LogisticAT() #Default parameters: alpha=1.0, verbose=0, maxiter=10000


In [11]:
#Code to read the data
data = pd.read_csv('C:\\Users\\Pavan\\Desktop\\rang\\movie_rating_prediction-master\\movie_metadata.csv', sep=',',header=0,encoding='latin-1')
data["genres_count"]=data.genres.str.split('|', 0).apply(lambda x: len(x))
data["plotkeyword_1"],data["plotkeyword_others"]=data.plot_keywords.str.split('|', 1).str
data["title_num_words"]=data.movie_title.str.split(' ', 0).apply(lambda x: len(x))
data["title_first_alpha_numeric"]=pd.DataFrame(data.movie_title.str.split(' ',1).tolist(),columns = ['first','other'])["first"].str[0]
#data.loc[:,["movie_title","genres","plot_keywords","genres_count","plotkeywords_count","plotkeyword_1","movie_title_word_length","movie_first_alpha_numeric"]]
data["imdb_score2"]=pd.cut(data['imdb_score'],[0,5.8,6.6,7.2,10],labels=[0,1,2,3]).astype("object")
data=data.dropna(axis=0, how='any')
data=data.drop("imdb_score",1)
data["imdb_score2"]=data.imdb_score2.astype("int64")

In [12]:
data["num_critic_for_reviews"]=pd.cut(data["num_critic_for_reviews"],[0, 50.0, 110.0, 195.0, 813.0],labels=[1, 2, 3, 4],include_lowest=True)
data["duration"]=pd.cut(data["duration"],[0, 93.0, 103.0, 118.0, 511.0],labels=[1, 2, 3, 4],include_lowest=True)
data["director_facebook_likes"]=pd.cut(data["director_facebook_likes"],[0, 7.0, 49.0, 194.5, 23000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_3_facebook_likes"]=pd.cut(data["actor_3_facebook_likes"],[0, 133.0, 371.5, 636.0, 23000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_1_facebook_likes"]=pd.cut(data["actor_1_facebook_likes"],[0, 614.0, 988.0, 11000.0, 640000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["gross"]=pd.cut(data["gross"],[0, 5340987.5, 25517500.0, 62309437.5, 760505847.0],labels=[1, 2, 3, 4],include_lowest=True)
data["num_voted_users"]=pd.cut(data["num_voted_users"],[0, 8593.5, 34359.0, 96309.0, 1689764.0],labels=[1, 2, 3, 4],include_lowest=True)
data["cast_total_facebook_likes"]=pd.cut(data["cast_total_facebook_likes"],[0, 1411.0, 3090.0, 13756.5, 656730.0],labels=[1, 2, 3, 4],include_lowest=True)
data["facenumber_in_poster"]=pd.cut(data["facenumber_in_poster"],[0, 1.0, 2.0, 43.0],labels=[1, 2, 3],include_lowest=True)
data["num_user_for_reviews"]=pd.cut(data["num_user_for_reviews"],[0, 65.0, 156.0, 326.0, 5060.0],labels=[1, 2, 3, 4],include_lowest=True)
data["budget"]=pd.cut(data["budget"],[0, 6000000.0, 20000000.0, 45000000.0, 12215500000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["title_year"]=pd.cut(data["title_year"],[0, 1999.0, 2005.0, 2011.0, 2016.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_2_facebook_likes"]=pd.cut(data["actor_2_facebook_likes"],[0, 281.0, 595.0, 918.0, 137000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["aspect_ratio"]=pd.cut(data["aspect_ratio"],[0, 1.85, 2.35, 16.0],labels=[1, 2, 3],include_lowest=True)
data["movie_facebook_likes"]=pd.cut(data["movie_facebook_likes"],[0, 166.0, 3000.0, 349000.0],labels=[1, 2, 3],include_lowest=True)
data["genres_count"]=pd.cut(data["genres_count"],[0, 2.0, 3.0, 4.0, 8.0],labels=[1, 2, 3, 4],include_lowest=True)
data["title_num_words"]=pd.cut(data["title_num_words"],[0, 2.0, 4.0, 20.0],labels=[1, 2, 3],include_lowest=True)

In [13]:
for col in data.columns:
    if(data[col].dtypes=="object"):
             data[col]=pd.factorize(data[col],na_sentinel=0)[0]

In [14]:
data_ordinal=data.copy()
X_train, X_test = train_test_split(data, test_size=0.3, random_state=223)
Y_train=X_train.pop("imdb_score2")
Y_test=X_test.pop("imdb_score2")

In [15]:
c.fit(X_train,Y_train)
y_pred = c.predict(X_test)

In [16]:
print("Confusion Matrix: ")
print (confusion_matrix(Y_test, y_pred))
    
print ("Accuracy : ",accuracy_score(Y_test,y_pred)*100)
 
print classification_report(Y_test, y_pred)


Confusion Matrix: 
[[116 110  44   2]
 [ 56 131 131   9]
 [ 26  61 155  34]
 [  7  21 127  95]]
('Accuracy : ', 44.177777777777777)
             precision    recall  f1-score   support

          0       0.57      0.43      0.49       272
          1       0.41      0.40      0.40       327
          2       0.34      0.56      0.42       276
          3       0.68      0.38      0.49       250

avg / total       0.49      0.44      0.45      1125



In [17]:
#Quality check

print("predicted",c.predict(data_ordinal.loc[1937,].drop("imdb_score2")))


('predicted', array([3]))


# Decision Tree

In [18]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

C:\Users\Pavan\Anaconda2\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [19]:
#Code to read the data
data = pd.read_csv('C:\\Users\\Pavan\\Desktop\\rang\\movie_rating_prediction-master\\movie_metadata.csv', sep=',',header=0,encoding='latin-1')
data["genres_count"]=data.genres.str.split('|', 0).apply(lambda x: len(x))
data["plotkeyword_1"],data["plotkeyword_others"]=data.plot_keywords.str.split('|', 1).str
data["title_num_words"]=data.movie_title.str.split(' ', 0).apply(lambda x: len(x))
data["title_first_alpha_numeric"]=pd.DataFrame(data.movie_title.str.split(' ',1).tolist(),columns = ['first','other'])["first"].str[0]
#data.loc[:,["movie_title","genres","plot_keywords","genres_count","plotkeywords_count","plotkeyword_1","movie_title_word_length","movie_first_alpha_numeric"]]
data["imdb_score2"]=pd.cut(data['imdb_score'],[0,5.8,6.6,7.2,10],labels=[0,1,2,3]).astype("object")
data=data.dropna(axis=0, how='any')
data=data.drop("imdb_score",1)
data["imdb_score2"]=data.imdb_score2.astype("int64")

In [20]:
for column in data.columns:
    if(data[column].dtypes!="object"):
             temp_values=[]
             temp1=pd.qcut(data[column], 4,duplicates='drop').cat.categories.right.values.tolist()
             temp1.insert(0,0)
             
             temp2=(range(1,(len(temp1)),1))
             #print(len(temp1))
             print("""data["%s"]=pd.cut(data["%s"],%s,labels=%s,include_lowest=True)""" %(column,column,temp1,temp2) )


data["num_critic_for_reviews"]=pd.cut(data["num_critic_for_reviews"],[0, 77.0, 139.0, 224.0, 813.0],labels=[1, 2, 3, 4],include_lowest=True)
data["duration"]=pd.cut(data["duration"],[0, 96.0, 106.0, 120.0, 330.0],labels=[1, 2, 3, 4],include_lowest=True)
data["director_facebook_likes"]=pd.cut(data["director_facebook_likes"],[0, 11.0, 64.0, 236.5, 23000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_3_facebook_likes"]=pd.cut(data["actor_3_facebook_likes"],[0, 195.0, 436.0, 691.0, 23000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_1_facebook_likes"]=pd.cut(data["actor_1_facebook_likes"],[0, 746.0, 1000.0, 13000.0, 640000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["gross"]=pd.cut(data["gross"],[0, 8325391.5, 30105968.0, 67005855.5, 760505847.0],labels=[1, 2, 3, 4],include_lowest=True)
data["num_voted_users"]=pd.cut(data["num_voted_users"],[0, 19712.0, 54077.0, 128688.0, 1689764.0],labels=[1, 2, 3, 4],include_lowest=True)
data["cast_total_facebook_likes"]=pd.cut(da

In [21]:
data["num_critic_for_reviews"]=pd.cut(data["num_critic_for_reviews"],[0, 50.0, 110.0, 195.0, 813.0],labels=[1, 2, 3, 4],include_lowest=True)
data["duration"]=pd.cut(data["duration"],[0, 93.0, 103.0, 118.0, 511.0],labels=[1, 2, 3, 4],include_lowest=True)
data["director_facebook_likes"]=pd.cut(data["director_facebook_likes"],[0, 7.0, 49.0, 194.5, 23000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_3_facebook_likes"]=pd.cut(data["actor_3_facebook_likes"],[0, 133.0, 371.5, 636.0, 23000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_1_facebook_likes"]=pd.cut(data["actor_1_facebook_likes"],[0, 614.0, 988.0, 11000.0, 640000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["gross"]=pd.cut(data["gross"],[0, 5340987.5, 25517500.0, 62309437.5, 760505847.0],labels=[1, 2, 3, 4],include_lowest=True)
data["num_voted_users"]=pd.cut(data["num_voted_users"],[0, 8593.5, 34359.0, 96309.0, 1689764.0],labels=[1, 2, 3, 4],include_lowest=True)
data["cast_total_facebook_likes"]=pd.cut(data["cast_total_facebook_likes"],[0, 1411.0, 3090.0, 13756.5, 656730.0],labels=[1, 2, 3, 4],include_lowest=True)
data["facenumber_in_poster"]=pd.cut(data["facenumber_in_poster"],[0, 1.0, 2.0, 43.0],labels=[1, 2, 3],include_lowest=True)
data["num_user_for_reviews"]=pd.cut(data["num_user_for_reviews"],[0, 65.0, 156.0, 326.0, 5060.0],labels=[1, 2, 3, 4],include_lowest=True)
data["budget"]=pd.cut(data["budget"],[0, 6000000.0, 20000000.0, 45000000.0, 12215500000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["title_year"]=pd.cut(data["title_year"],[0, 1999.0, 2005.0, 2011.0, 2016.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_2_facebook_likes"]=pd.cut(data["actor_2_facebook_likes"],[0, 281.0, 595.0, 918.0, 137000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["aspect_ratio"]=pd.cut(data["aspect_ratio"],[0, 1.85, 2.35, 16.0],labels=[1, 2, 3],include_lowest=True)
data["movie_facebook_likes"]=pd.cut(data["movie_facebook_likes"],[0, 166.0, 3000.0, 349000.0],labels=[1, 2, 3],include_lowest=True)
data["genres_count"]=pd.cut(data["genres_count"],[0, 2.0, 3.0, 4.0, 8.0],labels=[1, 2, 3, 4],include_lowest=True)
data["title_num_words"]=pd.cut(data["title_num_words"],[0, 2.0, 4.0, 20.0],labels=[1, 2, 3],include_lowest=True)

In [22]:
data=data.drop("actor_1_facebook_likes",1)
data=data.drop("actor_2_facebook_likes",1)
data=data.drop("actor_3_facebook_likes",1)
data=data.drop("director_name",1)
data=data.drop("actor_1_name",1)
data=data.drop("actor_2_name",1)
data=data.drop("actor_3_name",1)
data=data.drop("genres",1)
data=data.drop("movie_title",1)
data=data.drop("plot_keywords",1)
data=data.drop("plotkeyword_others",1)
data=data.drop("movie_imdb_link",1)
data=data.drop("country",1)
data=data.drop("num_critic_for_reviews",1)
data=data.drop("num_voted_users",1)
data=data.drop("genres_count",1)
data=data.drop("title_num_words",1)
data=data.drop("aspect_ratio",1)
data=data.drop("budget",1)
data=data.drop("facenumber_in_poster",1)
data=data.drop("cast_total_facebook_likes",1)
#data.columns


In [23]:
data=data.apply(lambda x : pd.factorize(x,na_sentinel=0)[0])
data_dtree=data.copy()
Y=data.pop("imdb_score2")

X=data
#X=data.loc[:,["duration","director_facebook_likes","num_critic_for_reviews","num_voted_users"]]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 223)

# Creating the classifier object 
clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=12, min_samples_leaf=5)

clf_gini.fit(X_train, y_train)



# Predicton on test with giniIndex
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

print("Confusion Matrix: ")
print (confusion_matrix(y_test, y_pred))
    
print ("Accuracy : ",accuracy_score(y_test,y_pred)*100)
 
print classification_report(y_test, y_pred)


Predicted values:
[2 0 2 ..., 2 2 2]
Confusion Matrix: 
[[138  57  38  17]
 [ 79  81  90  26]
 [ 51  83 141  52]
 [ 25  60  94  93]]
('Accuracy : ', 40.266666666666666)
             precision    recall  f1-score   support

          0       0.47      0.55      0.51       250
          1       0.29      0.29      0.29       276
          2       0.39      0.43      0.41       327
          3       0.49      0.34      0.40       272

avg / total       0.41      0.40      0.40      1125



In [25]:
#Quality check

print("predicted",clf_gini.predict(data_dtree.loc[1937:1938,].drop("imdb_score2",1)))


('predicted', array([0, 3], dtype=int64))


In [26]:
from sklearn import tree

tree.export_graphviz(clf_gini,out_file='tree.dot')
#data.iloc[:,12]

# Naive Bayes

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [28]:
#Code to read the data
data = pd.read_csv('C:\\Users\\Pavan\\Desktop\\rang\\movie_rating_prediction-master\\movie_metadata.csv', sep=',',header=0,encoding='latin-1')
data["genres_count"]=data.genres.str.split('|', 0).apply(lambda x: len(x))
data["plotkeyword_1"],data["plotkeyword_others"]=data.plot_keywords.str.split('|', 1).str
data["title_num_words"]=data.movie_title.str.split(' ', 0).apply(lambda x: len(x))
data["title_first_alpha_numeric"]=pd.DataFrame(data.movie_title.str.split(' ',1).tolist(),columns = ['first','other'])["first"].str[0]
#data.loc[:,["movie_title","genres","plot_keywords","genres_count","plotkeywords_count","plotkeyword_1","movie_title_word_length","movie_first_alpha_numeric"]]
data["imdb_score2"]=pd.cut(data['imdb_score'],[0,5.8,6.6,7.2,10],labels=[0,1,2,3]).astype("object")
data=data.dropna(axis=0, how='any')
data=data.drop("imdb_score",1)
data["imdb_score2"]=data.imdb_score2.astype("int64")

In [29]:
data["num_critic_for_reviews"]=pd.cut(data["num_critic_for_reviews"],[0, 50.0, 110.0, 195.0, 813.0],labels=[1, 2, 3, 4],include_lowest=True)
data["duration"]=pd.cut(data["duration"],[0, 93.0, 103.0, 118.0, 511.0],labels=[1, 2, 3, 4],include_lowest=True)
data["director_facebook_likes"]=pd.cut(data["director_facebook_likes"],[0, 7.0, 49.0, 194.5, 23000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_3_facebook_likes"]=pd.cut(data["actor_3_facebook_likes"],[0, 133.0, 371.5, 636.0, 23000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_1_facebook_likes"]=pd.cut(data["actor_1_facebook_likes"],[0, 614.0, 988.0, 11000.0, 640000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["gross"]=pd.cut(data["gross"],[0, 5340987.5, 25517500.0, 62309437.5, 760505847.0],labels=[1, 2, 3, 4],include_lowest=True)
data["num_voted_users"]=pd.cut(data["num_voted_users"],[0, 8593.5, 34359.0, 96309.0, 1689764.0],labels=[1, 2, 3, 4],include_lowest=True)
data["cast_total_facebook_likes"]=pd.cut(data["cast_total_facebook_likes"],[0, 1411.0, 3090.0, 13756.5, 656730.0],labels=[1, 2, 3, 4],include_lowest=True)
data["facenumber_in_poster"]=pd.cut(data["facenumber_in_poster"],[0, 1.0, 2.0, 43.0],labels=[1, 2, 3],include_lowest=True)
data["num_user_for_reviews"]=pd.cut(data["num_user_for_reviews"],[0, 65.0, 156.0, 326.0, 5060.0],labels=[1, 2, 3, 4],include_lowest=True)
data["budget"]=pd.cut(data["budget"],[0, 6000000.0, 20000000.0, 45000000.0, 12215500000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["title_year"]=pd.cut(data["title_year"],[0, 1999.0, 2005.0, 2011.0, 2016.0],labels=[1, 2, 3, 4],include_lowest=True)
data["actor_2_facebook_likes"]=pd.cut(data["actor_2_facebook_likes"],[0, 281.0, 595.0, 918.0, 137000.0],labels=[1, 2, 3, 4],include_lowest=True)
data["aspect_ratio"]=pd.cut(data["aspect_ratio"],[0, 1.85, 2.35, 16.0],labels=[1, 2, 3],include_lowest=True)
data["movie_facebook_likes"]=pd.cut(data["movie_facebook_likes"],[0, 166.0, 3000.0, 349000.0],labels=[1, 2, 3],include_lowest=True)
data["genres_count"]=pd.cut(data["genres_count"],[0, 2.0, 3.0, 4.0, 8.0],labels=[1, 2, 3, 4],include_lowest=True)
data["title_num_words"]=pd.cut(data["title_num_words"],[0, 2.0, 4.0, 20.0],labels=[1, 2, 3],include_lowest=True)

In [30]:
for col in data.columns:
    if(data[col].dtypes=="object"):
             data[col]=pd.factorize(data[col],na_sentinel=0)[0]

In [31]:
data_NB=data.copy()
X_train, X_test = train_test_split(data, test_size=0.3, random_state=223)

In [32]:
gnb = GaussianNB()
Y_train=X_train.pop("imdb_score2")
Y_test=X_test.pop("imdb_score2")

In [33]:
X_train.columns

Index([                    u'color',             u'director_name',
          u'num_critic_for_reviews',                  u'duration',
         u'director_facebook_likes',    u'actor_3_facebook_likes',
                    u'actor_2_name',    u'actor_1_facebook_likes',
                           u'gross',                    u'genres',
                    u'actor_1_name',               u'movie_title',
                 u'num_voted_users', u'cast_total_facebook_likes',
                    u'actor_3_name',      u'facenumber_in_poster',
                   u'plot_keywords',           u'movie_imdb_link',
            u'num_user_for_reviews',                  u'language',
                         u'country',            u'content_rating',
                          u'budget',                u'title_year',
          u'actor_2_facebook_likes',              u'aspect_ratio',
            u'movie_facebook_likes',              u'genres_count',
                   u'plotkeyword_1',        u'plotkeyword_othe

In [34]:
gnb.fit(
    X_train.values,
    Y_train)
y_pred = gnb.predict(X_test)
print("Confusion Matrix: ")
print (confusion_matrix(Y_test, y_pred))
    
print ("Accuracy : ",accuracy_score(Y_test,y_pred)*100)
 
print classification_report(Y_test, y_pred)


Confusion Matrix: 
[[231  31   4   6]
 [239  66   8  14]
 [156  67  18  35]
 [ 87  57  23  83]]
('Accuracy : ', 35.37777777777778)
             precision    recall  f1-score   support

          0       0.32      0.85      0.47       272
          1       0.30      0.20      0.24       327
          2       0.34      0.07      0.11       276
          3       0.60      0.33      0.43       250

avg / total       0.38      0.35      0.31      1125



In [35]:
#Quality check

print("predicted",gnb.predict(data_NB.loc[1937:1938,].drop("imdb_score2",1)))
data = pd.read_csv('C:\\Users\\Pavan\\Desktop\\rang\\movie_rating_prediction-master\\movie_metadata.csv', sep=',',header=0,encoding='latin-1')
data.loc[1937,]

('predicted', array([3, 0], dtype=int64))


color                                                                    Color
director_name                                                   Frank Darabont
num_critic_for_reviews                                                     199
duration                                                                   142
director_facebook_likes                                                      0
actor_3_facebook_likes                                                     461
actor_2_name                                                    Jeffrey DeMunn
actor_1_facebook_likes                                                   11000
gross                                                              2.83415e+07
genres                                                             Crime|Drama
actor_1_name                                                    Morgan Freeman
movie_title                                         The Shawshank Redemption 
num_voted_users                                     